FROM node:20-alpine AS build
WORKDIR /app

ARG APP_VERSION=0.0.0-dev
ARG REPO_URL=https://github.com/Xitee1/package-tracker
ENV APP_VERSION=${APP_VERSION}
ENV REPO_URL=${REPO_URL}

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
