"""add email_scans and scan_history_settings tables

Revision ID: 26cc9fb6568a
Revises: f526231b0a34
Create Date: 2026-02-14 08:09:55.385771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26cc9fb6568a'
down_revision: Union[str, Sequence[str], None] = 'f526231b0a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_history_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_age_days', sa.Integer(), nullable=False),
    sa.Column('max_per_user', sa.Integer(), nullable=False),
    sa.Column('cleanup_interval_hours', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('folder_path', sa.String(length=512), nullable=False),
    sa.Column('email_uid', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=512), nullable=False),
    sa.Column('subject', sa.String(length=1024), nullable=False),
    sa.Column('sender', sa.String(length=512), nullable=False),
    sa.Column('email_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), nullable=False),
    sa.Column('llm_raw_response', sa.JSON(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('rescan_queued', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['email_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_scans_message_id'), 'email_scans', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_scans_message_id'), table_name='email_scans')
    op.drop_table('email_scans')
    op.drop_table('scan_history_settings')
    # ### end Alembic commands ###
