"""add worker_stats table

Revision ID: f526231b0a34
Revises: f3e69a298ca7
Create Date: 2026-02-13 23:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f526231b0a34'
down_revision: Union[str, Sequence[str], None] = 'f3e69a298ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('hour_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('emails_processed', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['watched_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_id', 'hour_bucket', name='uq_worker_stats_folder_hour')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_stats')
    # ### end Alembic commands ###
