"""add imap settings

Revision ID: f3e69a298ca7
Revises: 9299dae441a6
Create Date: 2026-02-13 21:42:40.126994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e69a298ca7'
down_revision: Union[str, Sequence[str], None] = '9299dae441a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imap_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_email_age_days', sa.Integer(), nullable=False),
    sa.Column('processing_delay_sec', sa.Float(), nullable=False),
    sa.Column('check_uidvalidity', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('watched_folders', sa.Column('max_email_age_days', sa.Integer(), nullable=True))
    op.add_column('watched_folders', sa.Column('processing_delay_sec', sa.Float(), nullable=True))
    op.add_column('watched_folders', sa.Column('uidvalidity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watched_folders', 'uidvalidity')
    op.drop_column('watched_folders', 'processing_delay_sec')
    op.drop_column('watched_folders', 'max_email_age_days')
    op.drop_table('imap_settings')
    # ### end Alembic commands ###
